### ISSUE TITLE
OpenCV version

### ISSUE THREAD

**Issue by chazanov** [dkogan/mrgingham#1]
Which OpenCV version is needed?

My opencv4 includes are at /usr/include/opencv4/opencv2 – and are not found:
`Package 'opencv', required by 'virtual:world', not found`

**Comment by dkogan** [comment]
On March 16, 2019 12:12:45 PM CDT, chazanov <notifications@github.com> wrote:
>Which OpenCV version is needed?>
>>
>My opencv4 includes are at /usr/include/opencv4/opencv2 – and are not
>found:>
>`Package 'opencv', required by 'virtual:world', not found`>

Hi. Which distro are you using? So far I've used this only on centos 7 and various flavors of Debian.

**Comment by baerbock** [comment]
@dkogan I'm sustaining the same error and I'm on ArchLinux.

**Comment by dkogan** [comment]
On March 16, 2019 5:11:58 PM CDT, baerbock <notifications@github.com> wrote:
>@dkogan I'm sustaining the same error and I'm on ArchLinux.

OK. I'm not an arch linux user. Give me a few days to get to this. What is the exact arch-linux command to install this opencv library?

**Comment by baerbock** [comment]
`pacman -S opencv`

**Comment by dkogan** [comment]
OK, if you pull the latest code it'll mostly work on arch. The remaining issue is that the arch-linux opencv package is not providing pkg-config files. Please file a bug report with the maintainer of that package. This is where the `Package 'opencv', required by 'virtual:world', not found` error is coming from. You can work-around by applying this patch:

```diff --git a/Makefile b/Makefile
index 8f942c8..edb72b5 100644
--- a/Makefile
+++ b/Makefile
@@ -18,8 +18,8 @@ BIN_SOURCES += test-dump-chessboard-corners.cc test-dump-blobs.cc test-find-grid
 
 LIB_SOURCES := find_grid.cc find_blobs.cc find_chessboard_corners.cc mrgingham.cc ChESS.c
 
-CXXFLAGS_CV := $(shell pkg-config --cflags opencv)
-LDLIBS_CV   := $(shell pkg-config --libs   opencv)
+CXXFLAGS_CV := -I/usr/include/opencv4
+LDLIBS_CV   := -lopencv_imgproc -lopencv_imgcodecs -lopencv_features2d -lopencv_core
 CCXXFLAGS += $(CXXFLAGS_CV)
 LDLIBS    += $(LDLIBS_CV) -lpthread
 ```

I don't want to commit this because it only makes sense for opencv4 users on arch linux. If you have a better approach, let me know. The library should build then.

By the way, how did you find this? I haven't done any advertising at all.

**Comment by chazanov** [comment]
@dkogan I have big EARS and EYES and find everything...

When compiling mrgingham my OpenCV seems to be totally broken: https://pastebin.com/x4uikMS6
Weirdly I can actually use it via the Python API

**Comment by dkogan** [comment]
chazanov <notifications@github.com> writes:

> When compiling mrgingham my OpenCV seems to be totally broken: https://
> pastebin.com/x4uikMS6
> Weirdly I can actually use it via the Python API

I don't know what you ran to get this output. Can you please include the
full set of commands that got you to the errors?
