### ISSUE TITLE
Does it support N*M chessboard?

### ISSUE THREAD

**Issue by ShepherdSosimple** [dkogan/mrgingham#2]
Thanks for your excellent work. But does it support N*M chessboard?

**Comment by dkogan** [comment]
It does not, and I just pushed an update to the docs to further clarify
this point.

Supporting this would take a bit of work, and it's not obviously useful:
rectangular boards don't have any clear advantages over square ones.

If this is important to you, I can help you develop a patch. Otherwise,
I don't think this is useful to work on. In my opinion, a more valuable
thing to do would be to support partial board observations and to encode
a board orientation. Let me know if you want to work on that.

**Comment by dkogan** [comment]
Nobody is planning to work on this, so closing.
